# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-18.04"


  # start webserver VM
  config.vm.define "webserver" do |box|
    box.vm.hostname = "webserver"
    box.vm.network "private_network", ip: "192.168.33.10"

    box.vm.provider "virtualbox" do |vbox|
      vbox.name = "webserver"
      # Customize the amount of memory on the VM:
      vbox.memory = "1024"
    end

    box.vm.provision "shell", inline: <<-SHELL
apt-get update
apt-get install -y apache2 
SHELL

  end
  # end webserver VM
  
  # start database VM
  config.vm.define "database" do |box|
    box.vm.hostname = "database"
    box.vm.network "private_network", ip: "192.168.33.11"

    box.vm.provider "virtualbox" do |vbox|
      vbox.name = "database"
      # Customize the amount of memory on the VM:
      vbox.memory = "1024"
    end

    box.vm.provision "shell", inline: <<-SHELL
apt-get update
apt-get install -y mysql-server 
SHELL

  end
  # end database VM

end
